<a href="https://colab.research.google.com/github/aman-5137/DeadTorch/blob/main/_pyTorch_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Tensors**

In [2]:
import torch
print(torch.__version__)

2.11.0+cu128


In [4]:
# To check if GPU is available to me or not

if torch.cuda.is_available():
    print("GPU is available")
    print("The name of the GPU is", torch.cuda.get_device_name(0))
else:
    print("GPU is not available")


# Click on ram/disk on right to change from CPU to GPU or vice-versa

GPU is available
The name of the GPU is Tesla T4


In [5]:
# How to create an empty tensor

x = torch.empty(2,3)
print(x)


tensor([[5.5782e-01, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])


In [6]:
# What is the type is x?

type(x)

torch.Tensor

In [7]:
# Creating tensor that contains only zeros.

x = torch.zeros(2,3)
x

# NOTE: Here, 2 is columns and 3 is Rows

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# Same for 1s

x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
# How to get random value in torch?

x = torch.rand(2,3)
x

tensor([[0.7041, 0.5573, 0.6959],
        [0.9849, 0.2924, 0.4823]])

In [15]:
# Every time rand runs it generates new value, to control it we can use "manual_seed".

x = torch.manual_seed(10)
x= torch.rand(2,3)
x

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [19]:
# How can we create custome tensors?

x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
# Other ways to use tensor

# arange function
x = torch.arange(0, 10, 1)
x

# (0 : start, 10: (10-1) end, 2: gap)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# To get evenly spaced values in tensor

x = torch.linspace(0, 10, 10)
x

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [27]:
#  Identity metrics

x = torch.eye(5)
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [29]:
# torch.full

x = torch.full((3,3), 5)
x
# (3: column size, 3: row size, 5: element to store)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])